version: '3.8'

services:
  # Сервис для Weaviate
  weaviate:
    image: semitechnologies/weaviate:latest
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - ENABLE_MODULES='text2vec-cohere,text2vec-huggingface,text2vec-openai'
    ports:
      - "8080:8080"   # REST API
      - "50051:50051"  # gRPC
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always

  # Сервис для бэкенда
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    restart: always

  # Сервис для фронтенда
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always

volumes:
  weaviate_data:
