services:
  weaviate:
    image: semitechnologies/weaviate:latest
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
    ports:
      - "8080:8080"   # REST API
      - "50051:50051"  # gRPC
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
volumes:
  weaviate_data: